trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
jobs:
  - job: Tests
    container:
      image: xd009642/tarpaulin:latest
      options: --security-opt seccomp=unconfined
    steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        rustup update
        rustup component add rustfmt
      displayName: 'Install Rust'
    - script: cargo fmt --all -- --check
      displayName: Check formatting
    - script: cargo test --all-features
      displayName: 'Cargo Tests'
    - script: cargo tarpaulin --all-features --out Xml
      displayName: 'Code coverage'
    - script: bash <(curl -s https://codecov.io/bash)
      displayName: 'Upload coverage'
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)