[package]
name = "rvh"
version = "0.1.0"
authors = ["Lion Ackermann <ackerm.lion@hotmail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
